// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWN1eaduNcRYRJarVYX7HHsZ3dTBEJmZA',
    appId: '1:223448086780:android:99b037f07659d0af8ebf79',
    messagingSenderId: '223448086780',
    projectId: 'brainmemorizer',
    storageBucket: 'brainmemorizer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBurl_5pKN21yOc9cDR_8oi1fEFBBorXY8',
    appId: '1:223448086780:ios:ca2e92066c8536608ebf79',
    messagingSenderId: '223448086780',
    projectId: 'brainmemorizer',
    storageBucket: 'brainmemorizer.firebasestorage.app',
    iosBundleId: 'com.brainmemorizer.brainmemorizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBurl_5pKN21yOc9cDR_8oi1fEFBBorXY8',
    appId: '1:223448086780:ios:ca2e92066c8536608ebf79',
    messagingSenderId: '223448086780',
    projectId: 'brainmemorizer',
    storageBucket: 'brainmemorizer.firebasestorage.app',
    iosBundleId: 'com.brainmemorizer.brainmemorizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDynOL48EM4i6asesgFjVM0JLrl9Q-8vfY',
    appId: '1:223448086780:web:dbf63883a2eb62058ebf79',
    messagingSenderId: '223448086780',
    projectId: 'brainmemorizer',
    authDomain: 'brainmemorizer.firebaseapp.com',
    storageBucket: 'brainmemorizer.firebasestorage.app',
  );
}
